import React from 'react';
import Head from 'next/head';

export default function Checkout() {
  return (
    <div>
      <Head>
        <title>Checkout</title>
        <meta name="description" content="Generated by create next app" />
      </Head>


    </div>
  )
}
