import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Navbar from "@/components/organisms/Navbar";

export default function checkout() {
	const shadow = "shadow-[0_3px_5px_2px_rgba(0,0,0,0.2)]";
	const labelStyle = "text-[20px] font-bold";
  const totalPrice = 1000000
	const contentStyle = "line-clamp-2 overflow-ellipsis text-[15px] max-w-[300px]";
  const buttonSizing ="rounded-sm border-primary duration-[200ms] border-solid border-[1px] w-[150px] py-[15px] flex justify-center items-center text-[20px]"
		
	return (
		<>
			<Head>
				<title>Checkout</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Navbar onLanding={false} />
			<div className="top-0 left-0 flex overflow-hidden justify-center items-center">
				<div className="z-0 object-cover bg-darkgreen absolute top-0 h-full overflow-hidden">
					<Image
						src={"/assets/images/Library.webp"}
						alt=""
						width={4000}
						height={4000}
						className="opacity-50 object-right-bottom "
					/>
				</div>

				<div className={`flex z-10 h-screen top-0 absolute items-center justify-center `}>
					<section
						className={` bg-white ${shadow} flex rounded-[1rem] gap-[20px] overflow-hidden`}
					>
						{/*images */}
						<div>
							<Image
								src={"/assets/images/TestPic.jpg"}
								alt={""}
								width={400}
								height={400}
								className="aspect-auto w-[300px] "
							/>
						</div>
						<aside className="">
							<div className="flex flex-col py-[20px] pl-[20px] gap-[30px] pr-[50px] w-[400px]">
								<section className="flex flex-col">
									<h1 className=" font-bold text-[30px]">Confirm Payment</h1>
									<div>
										<h1 className={`${labelStyle}`}>Judul :</h1>
										<h2 className={`${contentStyle}`}>
											The Quick Brown Fox Jumps Over Lazy Dog Then Slips and
											falls on Lake and Suddenly Reincarnated As a Powerful
											Gumiho in another world. and also has a harem
										</h2>
									</div>
									<div>
										<h1 className={`${labelStyle}`}>Author</h1>
										<h2 className={`${contentStyle}`}>Average Anime Author</h2>
									</div>
								</section>
								<section className="flex flex-col gap-[5px] ">
									<div className="flex items-end justify-between border-b-[1px] border-primary">
										<h1 className="text-[30px]">Total :</h1>
										<div className="flex items-end gap-[10px]">
											<h1 className="text-[30px] -mb-[5px]">10</h1>
                      <p className="text[15px]">PCS</p>
										</div>
									</div>
                  <div className="flex justify-end gap-[30px] items-end overflow-hidden">
                    <h1 className=" text-[22px]">IDR</h1>
                    <h1 className=" text-[30px] bg-white flex" >{totalPrice}</h1>
                    
                  </div>
								</section>

                <section className="flex justify-between">
                  <button className={`${buttonSizing} text-primary  bg-transparent hover:bg-darkgreen hover:bg-opacity-40`}>Cancel</button>
                  <button className={`${buttonSizing} bg-primary text-green hover:border-[#115542] hover:bg-[#115542]`}>Confirm</button>
                </section>
							</div>
						</aside>
					</section>
				</div>
			</div>
		</>
	);
}
