import Head from "next/head";
import Navbar from "@/components/organisms/Navbar";
import Card from "@/components/molecule/Card"
import Hero from "@/components/organisms/Hero"

export default function Home() {
	return (
		<>
			<Head>
				<title>BookStore</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main className="flex flex-col">
				<Navbar />
				<Hero/>
				<div className="h-[1000px]">

				</div>
			</main>
		</>
	);
}