import Head from "next/head";
import Navbar from "@/components/organisms/Navbar";
import Card from "@/components/molecules/Card";
import Hero from "@/components/organisms/Hero";
import { getAllBooks } from "@/service/book";
import { BookTypes } from "@/types";
import { GetServerSideProps } from "next";

export default function Home({ books }: { books: BookTypes[] }) {
  return (
    <>
      <Head>
        <title>BookStore</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex flex-col">
        <Navbar onLanding={true} />
        <Hero />
        <section className="bg-darkgreen px-[100px] border-t-[24px] border-t-primary py-20 ">
          {books ? (
            <div className="grid grid-cols-4 gap-[40px] ">
              {books.map((book) => (
                <Card
                  key={book._id}
                  id={book._id}
                  title={book.title}
                  author={book.author}
                  source="TestPic.jpg"
                  price={book.price}
                />
              ))}
            </div>
          ) : (
            <p className="text-white text-center text-4xl font-bold w-fit mx-auto bg-primary px-12 py-24 my-10 rounded-lg ">
              Sorry, Currently We Ran Out of Book :(
            </p>
          )}
        </section>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const books: BookTypes[] = await getAllBooks().then((res) => res.data);

  return {
    props: {
      books,
    },
  };
};
