import Head from "next/head";
import React from "react";
import Input from "@/components/atom/Input";
import Image from "next/image";
import AuthButton from "@/components/atom/AuthButton";
import Link from "next/link";

export default function login() {
	return (
		<>
			<Head>
				<title>Login</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main className="flex h-screen items-center justify-center py-[100px] px-[180px] bg-gradient-to-r from-green to-primary ">
				<div className="flex grow h-[100%] shadow-[0_3px_8px_rgba(0,0,0,0.5)]">
					<div className="flex gap-[20px] w-[60%] bg-primary text-green text-[35px] items-end relative overflow-hidden">
						<Image
							src={"/assets/images/Library.jpg"}
							alt=""
							width={1000}
							height={1000}
							className="object-fill opacity-60"
						/>

						<div className="p-10 z-10 absolute flex gap-4 	 ">
							<Image
								src={"/assets/logos/Bookstore.svg"}
								alt="images"
								width={120}
								height={120}
								className=""
							/>
							<h1 className="w-fit ">Bookstore</h1>
						</div>
					</div>
					<div className="flex flex-col grow py-10 px-[80px] justify-center bg-white gap-[50px]">
						<h1 className="text-darkgreen font-semibold text-[40px] text-center">
							Sign In
						</h1>
						<div className="flex flex-col gap-[20px]">
							<Input label="" placeholder="Username" icon="user.svg" />
							<Input label="" placeholder="Password" icon="locks.svg" />
							<div className="flex justify-between text-darkgreen text-[12px] ">
								<div className="flex gap-[5px]">
									<input type="checkbox"></input>
									<p>Remember Me</p>
								</div>
								<p>Forgot Password?</p>
							</div>
						</div>
						<div className="flex justify-center">
							<AuthButton fill={'Sign In'}/>
						</div>
						<div className="flex self-center gap-1 text-[15px]">
							<p>New to Bookstore?</p><Link href={'signup'} className="text-green font-bold hover:underline ">Create Account</Link>
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
