import { useState } from "react";

import Head from "next/head";
import Image from "next/image";

import SignupForm from "@/components/organisms/SignupForm";

export default function SignUp() {
  return (
    <>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex h-screen items-center justify-center py-[70px] px-[180px] bg-gradient-to-r from-darkgreen to-primary ">
        <div className="flex grow h-[100%] shadow-[0_3px_8px_rgba(0,0,0,0.5)]">
          <div className="flex gap-[20px] w-[60%] bg-primary text-green text-[35px] items-end relative overflow-hidden">
            <Image
              src={"/assets/images/Library.jpg"}
              alt=""
              width={1000}
              height={1000}
              className="object-fill opacity-60"
            />

            <div className="p-10 z-10 absolute flex gap-4">
              <Image
                src={"/assets/logos/Bookstore.svg"}
                alt="images"
                width={120}
                height={120}
                className=""
              />
              <h1 className="w-fit ">Bookstore</h1>
            </div>
          </div>
          <SignupForm />
        </div>
      </main>
    </>
  );
}
